### ISSUE TITLE
Dropping wrong ores

### ISSUE THREAD

**Issue by TimGoll** [RCXcrafter/AOBDorechunks#5]
Maybe yours or of the basemod.
Immersive Engineering Bauxtide drops aluminum and Osmium has the same texture like Tin

**Comment by RCXcrafter** [comment]
Bauxite is actually a different name for aluminum ore so that's working fine.
Osmium having the same texture as tin is because they have a very similar color. The color for each texture is automatically generated by AOBD or JAOPCA (depending on which version you use), you can change this color in the config for aobdOrechunks/jaopca with a hexadecimal color code..
